// <auto-generated />
namespace Ams2PrototypeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedActiveDateCreatedDateUpdatedtoVehiclemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedActiveDateCreatedDateUpdatedtoVehiclemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291111288_Added Active, DateCreated, DateUpdated to Vehicle model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
