// <auto-generated />
namespace Ams2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedvirtualtoAssetinEquipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedvirtualtoAssetinEquipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041425402_Added virtual to Asset in Equipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
