// <auto-generated />
namespace Ams2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedcodeyearmake_mfgmodeltoequipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcodeyearmake_mfgmodeltoequipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201807111711512_added code,year,make_mfg,model to equipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
