// <auto-generated />
namespace Ams2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedlicenseplatetovehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedlicenseplatetovehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "201805080927170_Added license plate to vehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
