// <auto-generated />
namespace Ams2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedpropertytoincludeaddresscitystatezip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedpropertytoincludeaddresscitystatezip));
        
        string IMigrationMetadata.Id
        {
            get { return "201807141747068_changed property to include address,city,state,zip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
