// <auto-generated />
namespace Ams2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedAddressandFKtoAddressinAsset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedAddressandFKtoAddressinAsset));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291304159_added Address and FK to Address in Asset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
